<#
.SYNOPSIS
 A small PowerShell helper to automate the Git lab steps from `prompt.md`.

.DESCRIPTION
 - Checks for Git installation
 - Optionally sets global user.name and user.email
 - Initializes a repository (if not already a repo)
 - Creates a sample file if missing, stages and commits
 - Optionally adds a remote and pushes to `main`

.NOTES
 Run this script from the project root where you want the repo initialized.
#>

param(
    [string]$UserName,
    [string]$UserEmail,
    [string]$RemoteUrl,
    [switch]$Push
)

function ExitWithError([string]$msg, [int]$code = 1) {
    Write-Host "ERROR: $msg" -ForegroundColor Red
    exit $code
}

Write-Host "Starting Git init helper..."

# Check for git
if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
    ExitWithError "Git executable not found in PATH. Please install Git and try again."
}

Write-Host "Git found: $(git --version)"

# Optionally configure global username/email (only set if both provided)
if ($UserName -and $UserEmail) {
    Write-Host "Configuring global user.name and user.email..."
    git config --global user.name "$UserName"
    git config --global user.email "$UserEmail"
    Write-Host "Configured:
    user.name = $(git config --global user.name)
    user.email = $(git config --global user.email)"
} elseif ($UserName -or $UserEmail) {
    Write-Host "Partial identity provided. Provide both -UserName and -UserEmail to set both global values." -ForegroundColor Yellow
}

# Initialize repo if needed
if (-not (Test-Path -Path .git -PathType Container)) {
    Write-Host "Initializing new git repository..."
    git init
} else {
    Write-Host "Existing git repository detected. Skipping git init."
}

# Create a sample file if none exists (index.html)
$sample = "index.html"
if (-not (Test-Path -Path $sample)) {
    Write-Host "Creating sample file: $sample"
    @"
<!doctype html>
<html>
  <head>
    <meta charset=\"utf-8\" />
    <title>Sample Project</title>
  </head>
  <body>
    <h1>Sample Project</h1>
    <p>This file was generated by scripts/init-repo.ps1</p>
  </body>
</html>
"@ | Out-File -FilePath $sample -Encoding utf8
} else {
    Write-Host "$sample already exists; leaving it alone."
}

# Ensure .gitignore exists with a few common entries
$gitignore = ".gitignore"
if (-not (Test-Path -Path $gitignore)) {
    @"
# Ignore node modules and common OS files
node_modules/
.env
*.log
.DS_Store
Thumbs.db
"@ | Out-File -FilePath $gitignore -Encoding utf8
    Write-Host "Created $gitignore"
}

Write-Host "Staging files..."
git add .

Write-Host "Creating commit..."
try {
    $commitMessage = "Initial commit"
    git commit -m $commitMessage 2>$null
    if ($LASTEXITCODE -ne 0) {
        Write-Host "No changes to commit (or commit failed). Verify staged files and try again." -ForegroundColor Yellow
    } else {
        Write-Host "Committed: $commitMessage"
    }
} catch {
    Write-Host "Commit failed: $_" -ForegroundColor Red
}

if ($RemoteUrl) {
    Write-Host "Adding remote origin: $RemoteUrl"
    # If remote named origin already exists, warn and skip
    $existing = git remote
    if ($existing -match "origin") {
        Write-Host "Remote 'origin' already exists. To replace it, run: git remote remove origin; git remote add origin $RemoteUrl" -ForegroundColor Yellow
    } else {
        git remote add origin $RemoteUrl
        Write-Host "Remote 'origin' added. Verified with:"
        git remote -v
    }

    Write-Host "Ensuring branch name 'main' (creates or renames current branch)..."
    git branch -M main

    if ($Push) {
        Write-Host "Pushing to origin/main (you may be prompted for credentials)..."
        try {
            git push -u origin main
            if ($LASTEXITCODE -eq 0) {
                Write-Host "Push succeeded."
            } else {
                Write-Host "Push exited with code $LASTEXITCODE. Check your network/authentication." -ForegroundColor Yellow
            }
        } catch {
            Write-Host "Push failed: $_" -ForegroundColor Red
        }
    } else {
        Write-Host "Push not requested. If you want to push now, run: git push -u origin main"
    }
}

Write-Host "Done. Review git status with: git status"
